// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VMS.DataModel.DAL;

namespace VMS.DataModel.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VMS.DataModel.Entities.BlackList", b =>
                {
                    b.Property<int>("BlackListKey")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("Created");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("EndDate")
                        .IsRequired();

                    b.Property<byte>("IsDeleted");

                    b.Property<DateTime?>("Modified");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime?>("StartDate")
                        .IsRequired();

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("BlackListKey");

                    b.ToTable("BlackList");
                });

            modelBuilder.Entity("VMS.DataModel.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentKey")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<byte>("IsDeleted");

                    b.Property<DateTime?>("Modified");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50);

                    b.HasKey("DepartmentKey");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("VMS.DataModel.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeKey")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comments")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("Created");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50);

                    b.Property<int>("DepartmentKey");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(50);

                    b.Property<string>("Image")
                        .HasMaxLength(100);

                    b.Property<byte>("IsDeleted");

                    b.Property<string>("MobilePhone")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("Modified");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("OfficePhone")
                        .HasMaxLength(50);

                    b.Property<string>("OfficePhoneExt")
                        .HasMaxLength(50);

                    b.HasKey("EmployeeKey");

                    b.HasIndex("DepartmentKey");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("VMS.DataModel.Entities.EmployeeRequest", b =>
                {
                    b.Property<int>("EmployeeRequestKey")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("BeginDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan?>("BeginTime");

                    b.Property<string>("Comments")
                        .HasMaxLength(100);

                    b.Property<string>("Company")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("Created");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50);

                    b.Property<int>("EmployeeKey");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan?>("EndTime");

                    b.Property<byte>("IsDeleted");

                    b.Property<DateTime?>("Modified");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50);

                    b.Property<int>("PurposeKey");

                    b.Property<int>("Status");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(50);

                    b.Property<string>("VisitorEmail")
                        .HasMaxLength(50);

                    b.Property<string>("VisitorName")
                        .HasMaxLength(50);

                    b.Property<string>("VisitorPhone")
                        .HasMaxLength(50);

                    b.HasKey("EmployeeRequestKey");

                    b.HasIndex("EmployeeKey");

                    b.HasIndex("PurposeKey");

                    b.ToTable("EmployeeRequest");
                });

            modelBuilder.Entity("VMS.DataModel.Entities.Purpose", b =>
                {
                    b.Property<int>("PurposeKey")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<byte>("IsDeleted");

                    b.Property<DateTime?>("Modified");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50);

                    b.HasKey("PurposeKey");

                    b.ToTable("Purpose");
                });

            modelBuilder.Entity("VMS.DataModel.Entities.Visitor", b =>
                {
                    b.Property<int>("VisitorKey")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Company")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("Created");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("DatetimeIn");

                    b.Property<DateTime?>("DatetimeOut");

                    b.Property<string>("Email")
                        .HasMaxLength(50);

                    b.Property<int>("EmployeeKey");

                    b.Property<int>("EmployeeRequestKey");

                    b.Property<int>("Gender");

                    b.Property<string>("Image");

                    b.Property<byte>("IsDeleted");

                    b.Property<DateTime?>("Modified");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("PurposeComment")
                        .HasMaxLength(100);

                    b.Property<int>("PurposeKey");

                    b.Property<int>("Status");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("TaxNumberVisitor")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("VisitorKey");

                    b.HasIndex("EmployeeKey");

                    b.HasIndex("EmployeeRequestKey");

                    b.HasIndex("PurposeKey");

                    b.ToTable("Visitor");
                });

            modelBuilder.Entity("VMS.DataModel.Entities.Employee", b =>
                {
                    b.HasOne("VMS.DataModel.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentKey")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("VMS.DataModel.Entities.EmployeeRequest", b =>
                {
                    b.HasOne("VMS.DataModel.Entities.Employee", "Employee")
                        .WithMany("EmployeeRequests")
                        .HasForeignKey("EmployeeKey")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VMS.DataModel.Entities.Purpose", "Purpose")
                        .WithMany("EmployeeRequests")
                        .HasForeignKey("PurposeKey")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("VMS.DataModel.Entities.Visitor", b =>
                {
                    b.HasOne("VMS.DataModel.Entities.Employee", "Employee")
                        .WithMany("Visitors")
                        .HasForeignKey("EmployeeKey")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VMS.DataModel.Entities.EmployeeRequest", "EmployeeRequest")
                        .WithMany()
                        .HasForeignKey("EmployeeRequestKey")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VMS.DataModel.Entities.Purpose", "Purpose")
                        .WithMany("Visitors")
                        .HasForeignKey("PurposeKey")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
